language: python
python:
  - "3.9"

# command to install dependencies
install:
  - pip install -r private/miconsu/requirements.txt

# command to run tests
script:
  - cd private/miconsu
  - coverage run manage.py test
  - coverage report
  - coveralls