# Generated by Django 4.0.5 on 2022-07-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_client_client_plan_alter_client_client_type'),
        ('users', '0002_profile_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='client.client', verbose_name='Cliente'),
        ),
    ]
