# Generated by Django 4.0.5 on 2022-07-04 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('dni', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MASCULINE', 'Masculino'), ('FEMENINE', 'Femenino'), ('OTHER', 'Otro')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Soltero'), ('MARRIED', 'Casado'), ('CONCUBINE', 'Concubine'), ('DIVORCED', 'Separado/Divorciado'), ('WIDOW', 'Viudo')], max_length=30, null=True)),
                ('level_of_studies', models.CharField(blank=True, choices=[('ILLITERATE', 'Analfabeto'), ('PRIMARY_INCOMPLETE', 'Primario incompleto'), ('PRIMARY_COMPLETE', 'Primario completo'), ('SECONDARY_INCOMPLETE', 'Secundario incompleto'), ('SECONDARY_COMPLETE', 'Secundario completo'), ('TERTIARY_INCOMPLETE', 'Terciario incompleto'), ('TERTIARY_COMPLETE', 'Terciario completo')], max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.metadata')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
