# Generated by Django 4.0.5 on 2022-06-04 14:43

from django.db import migrations, models
import django.db.models.deletion
import person.enum.gender
import person.enum.level_of_studies
import person.enum.marital_status


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('dni', models.CharField(blank=True, max_length=25, null=True)),
                ('gender', models.CharField(blank=True, choices=[(person.enum.gender.GenderEnum['MASCULINE'], 'Masculino'), (person.enum.gender.GenderEnum['FEMENINE'], 'Femenino'), (person.enum.gender.GenderEnum['OTHER'], 'Otro')], max_length=20, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('marital_status', models.CharField(blank=True, choices=[(person.enum.marital_status.MaritalStatusEnum['SINGLE'], 'Soltero'), (person.enum.marital_status.MaritalStatusEnum['MARRIED'], 'Casado'), (person.enum.marital_status.MaritalStatusEnum['CONCUBINE'], 'Concubine'), (person.enum.marital_status.MaritalStatusEnum['DIVORCED'], 'Separado/Divorciado'), (person.enum.marital_status.MaritalStatusEnum['WIDOW'], 'Viudo')], max_length=30, null=True)),
                ('level_of_studies', models.CharField(blank=True, choices=[(person.enum.level_of_studies.LevelOfStudiesEnum['ILLITERATE'], 'Analfabeto'), (person.enum.level_of_studies.LevelOfStudiesEnum['PRIMARY_INCOMPLETE'], 'Primario incompleto'), (person.enum.level_of_studies.LevelOfStudiesEnum['PRIMARY_COMPLETE'], 'Primario completo'), (person.enum.level_of_studies.LevelOfStudiesEnum['SECONDARY_INCOMPLETE'], 'Secundario incompleto'), (person.enum.level_of_studies.LevelOfStudiesEnum['SECONDARY_COMPLETE'], 'Secundario completo'), (person.enum.level_of_studies.LevelOfStudiesEnum['TERTIARY_INCOMPLETE'], 'Terciario incompleto'), (person.enum.level_of_studies.LevelOfStudiesEnum['TERTIARY_COMPLETE'], 'Terciario completo')], max_length=30, null=True)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('metadata', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.metadata')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
        ),
    ]
