# Generated by Django 4.0.5 on 2022-06-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='slug',
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINE', 'Masculino'), ('FEMENINE', 'Femenino'), ('OTHER', 'Otro')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='level_of_studies',
            field=models.CharField(blank=True, choices=[('ILLITERATE', 'Analfabeto'), ('PRIMARY_INCOMPLETE', 'Primario incompleto'), ('PRIMARY_COMPLETE', 'Primario completo'), ('SECONDARY_INCOMPLETE', 'Secundario incompleto'), ('SECONDARY_COMPLETE', 'Secundario completo'), ('TERTIARY_INCOMPLETE', 'Terciario incompleto'), ('TERTIARY_COMPLETE', 'Terciario completo')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('SINGLE', 'Soltero'), ('MARRIED', 'Casado'), ('CONCUBINE', 'Concubine'), ('DIVORCED', 'Separado/Divorciado'), ('WIDOW', 'Viudo')], max_length=30, null=True),
        ),
    ]
