# Generated by Django 4.0.5 on 2022-06-04 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_metadata_client'),
        ('person', '0003_remove_person_id_alter_person_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='metadata.metadata'),
        ),
    ]
