export const environment = {
    production: false,
    apiUrl: '',

    apiUrlAppointment: 'api/appointment/',
    apiUrlAppointmentEvent: 'api/event/',
    apiUrlAppointmentByPatientId: '/api/appointments-by-patient-id/',
    apiUrlAddress: 'api/address/',
    apiUrlAgreement: 'api/agreement/',
    apiUrlCalendar: 'api/calendar/',
    apiUrlClient: 'api/client/',
    apiUrlClientPlan: 'api/client-plan/',
    apiUrlClientType: 'api/client-type/',
    apiUrlEmail: 'api/email/',
    apiUrlInsuranceProfessional: 'api/insurance-professional/',
    apiUrlInsurance: 'api/insurance/',
    apiUrlLocation: 'api/location/',
    apiUrlLogin: "api/token/",
    apiUrlOrganization: "api/organization/",
    apiUrlOrganizationalService: "api/organizational-service/",
    apiUrlPatient: 'api/patient/',
    apiUrlPayment: 'api/payment/',
    apiUrlPaymentMethod: 'api/payment-method/',
    apiUrlPerson: 'api/person/',
    apiUrlPhone: 'api/phone/',
    apiUrlPrescription: 'api/prescription/',
    apiUrlProfessional: 'api/professional/',
    apiUrlProfile: "api/profile/",
    apiUrlReferrer: "api/referrer/",
    apiUrlRegister: "api/register/",
    apiUrlService: "api/professional-service/",
    apiUrlUser: "api/user/",
  };