export const environment = {
  production: true,
  apiUrl: '',
  apiUrlAddress: '',
  apiUrlAgreement: '',
  apiUrlAppointment: '',
  apiUrlAppointmentEvent: '',
  apiUrlAppointmentByPatientId: '',
  apiUrlCalendar: '',
  apiUrlClient: '',
  apiUrlClientPlan: 'api/client-plan/',
  apiUrlClientType: '',
  apiUrlEmail: '',
  apiUrlInsurance: '',
  apiUrlInsuranceProfessional: '',
  apiUrlLocation: '',
  apiUrlLogin: '',
  apiUrlOrganization: '',
  apiUrlOrganizationalService: '',
  apiUrlPatient: '',
  apiUrlPayment: '',
  apiUrlPaymentMethod: '',
  apiUrlPerson: '',
  apiUrlPhone: '',
  apiUrlPrescription: '',
  apiUrlProfessional: '',
  apiUrlProfile: '',
  apiUrlRegister: '',
  apiUrlReferrer: '',
  apiUrlService: '',
  apiUrlUser: '',

};
